import{a as w,S as E,i as f}from"./assets/vendor-tnUJPedx.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const q="48807369-8911b207443a7f439467dae3a",S="https://pixabay.com/api/";let m=1,g=0;const y=async(t,r=!1)=>{r&&(m=1,g=0);try{const o=await w.get(`${S}`,{params:{key:q,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:m,per_page:40}});return r&&(g=o.data.totalHits),m+=1,{hits:o.data.hits,totalHits:o.data.totalHits}}catch(o){return console.error("Error fetching images:",o),{hits:[],totalHits:0}}},$=new E(".gallery a"),p=(t,r,o=!1)=>{if(t.length===0){f.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}const i=t.map(({webformatURL:e,largeImageURL:s,tags:a,likes:L,views:b,comments:v,downloads:H})=>`
        <a href="${s}" class="gallery__item">
          <img src="${e}" alt="${a}" loading="lazy" />
          <div class="info">
            <p class="info-item"><b>Likes:</b> ${L}</p>
            <p class="info-item"><b>Views:</b> ${b}</p>
            <p class="info-item"><b>Comments:</b> ${v}</p>
            <p class="info-item"><b>Downloads:</b> ${H}</p>
          </div>
        </a>
      `).join("");o?r.insertAdjacentHTML("beforeend",i):r.innerHTML=i,$.refresh()},I=document.querySelector("#search-form"),h=document.querySelector(".gallery"),u=document.querySelector(".loader"),n=document.querySelector(".load-more");let c="",d=0,l=0;const P=async t=>{if(t.preventDefault(),c=t.target.elements.searchQuery.value.trim(),!c){f.warning({title:"Warning",message:"Please enter a search query!"});return}n.classList.add("is-hidden"),u.classList.remove("is-hidden"),h.innerHTML="",l=0;try{const{hits:r,totalHits:o}=await y(c,!0);d=o,p(r,h),l+=r.length,l<d?n.classList.remove("is-hidden"):d>0&&(n.classList.add("is-hidden"),f.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}catch(r){console.error("Error handling search:",r)}finally{u.classList.add("is-hidden")}},M=async()=>{u.classList.remove("is-hidden");try{const{hits:t}=await y(c);p(t,h,!0),l+=t.length,window.scrollBy({top:h.firstElementChild.getBoundingClientRect().height*2,behavior:"smooth"}),(l>=d||t.length<40)&&(n.classList.add("is-hidden"),f.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}catch(t){console.error("Error loading more images:",t)}finally{u.classList.add("is-hidden")}};I.addEventListener("submit",P);n.addEventListener("click",M);
//# sourceMappingURL=index.js.map
